### ISSUE TITLE
居中方法

### ISSUE THREAD

**Issue by gutenye** [ywyanbin/learn#1]
Way 1

```html
<div class='container1'>
  <div class='content1'>
   hello
  </div>
</div>
```

```css
.container1 {
  display: flex;
  justify-content: center;
}
.content1 {
  width: 80%;
}
```

Way 2

```html
<div class='content'>
  hello
</div>
```

```css
.content {
  width: 80%;
  margin: 0 auto;
}
```
